### PR TITLE
added desktop calculator version1.2

### PR DESCRIPTION
**Pull request by ArturZalutskyi**
review that awesome code, this is something amazing

### CODE REVIEW

**Comment by LytvynOlena** [comment]
I did not write it here

**Comment by LytvynOlena** [comment]
Yes you are awesome too bro =)

**Comment by ArturZalutskyi** [comment]
god damn, create package with your name and add some code!!

**Comment by LytvynOlena** [comment]
I answer

**Comment by ArturZalutskyi** [comment]
here are no picktures, will be hard to collaborate with others

**Pull request merged**
